version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: drones-delivery-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: drones_delivery_db
    command: ["postgres", "-c", "max_connections=300", "-c", "shared_buffers=1024MB"]
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drones-delivery-app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/drones_delivery_db
    volumes:
      - .:/app